language: generic
sudo: required
branches:
  only:
  - master
services:
  - docker
script:
  - heroku container:login
  - heroku container:push web -a dou-hunter-bot
  - heroku container:release web -a dou-hunter-bot
