language: node_js
node_js:
  - "stable"
script:
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: VhLoqsX9uiNJ7TDC/qsd8bf4EZCafehkA+0QPMETCqVNJFwJRiJh+h+oRxb4Kv1vLtxbvw0SYJQgS6+3ZoCmPM9Unc/VABsLzQmbpe8FFXApT+OTeCmP3QK6+5DQvw1wpj0Q7Jx2gIDe+iiIF9/KKnb6JTKsWgEoT6SQYXFKFx+nmCiULYvmvrLMKdAFW3u0YsomsJRHU17mSdBOgcKHbDxJlahOjym54uHQMVVjDVVyi9FighepoSRXbWKGs1WpxmfRL0SP7huIkSnwIK9cbYzAsDU6qVmk4+jNgHx9GmI4itI1XknOp84fgaG28qwlCe9dX1fTYHKniRTG1hEoUX3C7rObWkEUJ/dWgDnrH0hww7q/HIP8FVxMXGAGx7Btd0pAaj10e7IDc8rp5iFlNQcMQeZFzKmeV4ZDkqLy5bFq+kx8AsVJdyDtwlRInX4ApLliQPhJ+N2CH+816b9d36w/Igvu+9AgyHjMPqB29ceNztdHwxk7e2r9u/KOmwVHM0Jgr2ndoCFpbZ3dUc5Q/xPk8HT2tSPEPwkXcITle17VlfHuz5nNUYDHgENApVdKo7Vq9fRdsn6l/4Sz6Jh8ZjwzX9GxTwslZdLc1nOq4nUBAbhvPYiIemJ0tK087sL1Kv6ganYNHe3pnF+GeqGzFu6ZVUX6hvpVE8JQbHPFuzE=
